webern-unibas-ch/awg-app

.github/workflows/visualize-repo.yml

This PR adds a repo token to visualize repo workflow.
Cf. https://blog.robsewell.com/blog/github-action-workflow-protected-branch-update-failed/

ci(gh-actions): update visualize-repo.yml

---

README.md

This PR updates the codecov badge in the README to not use the main-branch-specific badge.

docs(README): update codecov badge

---

README.md

This short PR fixes a typo in the TOC of the README.

docs(README): fix typo in TOC

---

.eslintrc.json
src/app/app.component.spec.ts
src/app/core/services/conversion-service/conversion.service.spec.ts
src/app/core/services/conversion-service/conversion.service.ts
src/app/views/data-view/data-outlets/search-panel/search-result-list/search-result-list.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-complex.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-graph/graph-visualizer/select-results/select-results.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-graph/graph-visualizer/sparql-table/sparql-table.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-list/source-list.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-series-detail/edition-series-detail.component.spec.ts

This PR simplifies the conversion logic for the full text search response and adds tests for it.
It fixes some linting errors on the fly.

fix(core): simplify conversion of full text search response

---

src/app/core/services/utility-service/utility.service.spec.ts
src/app/core/services/utility-service/utility.service.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/textcritics-list/textcritics-list.component.html
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/textcritics-list/textcritics-list.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/textcritics-list/textcritics-list.component.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-footer/edition-svg-sheet-footer.component.html
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-footer/edition-svg-sheet-footer.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-footer/edition-svg-sheet-footer.component.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-viewer/edition-svg-sheet-viewer-switch/edition-svg-sheet-viewer-switch.component.html
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-viewer/edition-svg-sheet-viewer-switch/edition-svg-sheet-viewer-switch.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-viewer/edition-svg-sheet-viewer-switch/edition-svg-sheet-viewer-switch.component.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-viewer/edition-svg-sheet-viewer.component.html
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-viewer/edition-svg-sheet-viewer.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-viewer/edition-svg-sheet-viewer.module.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-tka/edition-tka-label/edition-tka-label.component.html
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-tka/edition-tka-label/edition-tka-label.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-tka/edition-tka-label/edition-tka-label.component.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-tka/edition-tka-label/index.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-tka/edition-tka-table/edition-tka-table.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-tka/edition-tka-table/edition-tka-table.component.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-tka/edition-tka.module.ts

This PRs refactors the way how the textritic labels are applied depending on the id of current sheet or textcritics: 
It moves all the logic into a separate tka label component which is then used in all the needed places. This way the logic does not need to be duplicated in different parts of the app.

refactor(edition): refactor application of textcritic labels

---

src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-footer/edition-svg-sheet-footer.component.html
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-footer/edition-svg-sheet-footer.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-footer/edition-svg-sheet-footer.component.ts

This PR changes the up arrow to down arrow in the SvgSheetFooterComponent. This makes the behaviour more consistent with other (similar) elements.

fix(edition): fix direction of arrows in SheetFooter

---

src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-footer/edition-svg-sheet-footer.component.spec.ts

This PR removes an oversight in the SheetFooter test.

test(edition): fix test limitation

---

src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-viewer/edition-svg-sheet-viewer-nav/edition-svg-sheet-viewer-nav.component.html
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-viewer/edition-svg-sheet-viewer-nav/edition-svg-sheet-viewer-nav.component.scss
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-viewer/edition-svg-sheet-viewer-nav/edition-svg-sheet-viewer-nav.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-viewer/edition-svg-sheet-viewer-nav/edition-svg-sheet-viewer-nav.component.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-viewer/edition-svg-sheet-viewer-nav/index.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-viewer/edition-svg-sheet-viewer.component.html
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-viewer/edition-svg-sheet-viewer.component.scss
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-viewer/edition-svg-sheet-viewer.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-viewer/edition-svg-sheet-viewer.module.ts

This PR separates the logic for the navigation panels of the svg sheet viewer into a separate component.

refactor(edition): move sheet viewer nav into separate component

---

src/assets/data/edition/series/2/section/2a/m22/source-description.json

Dieser PR markiert die auf dem Kopf stehenden Skizzen von M22 und anderen als solche, analog zu identischen Fällen in op. 12.

fix(assets): mark reversed systems in m22

---

src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description.component.html
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-footer/edition-svg-sheet-footer.component.html
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-footer/edition-svg-sheet-footer.component.spec.ts
src/assets/themes/scss/main.scss
src/testing/mock-data/mockEditionData.ts

This PR removes the colon after a system unit if no systemdescription, measure or row is given.
It also renames some css-classes and fixes track-by indices in SourceDescComponent.
It also refactors the display of the EvaluationLabel in the SvgSheetFooter.

fix(edition): fix colons in system units of source descriptions

---

src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/edition-report.component.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-evaluation/source-evaluation.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-evaluation/source-evaluation.component.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-nav/edition-svg-sheet-nav-item/edition-svg-sheet-nav-item.component.html
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-nav/edition-svg-sheet-nav-item/edition-svg-sheet-nav-item.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-nav/edition-svg-sheet-nav-item/edition-svg-sheet-nav-item.component.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-convolute/edition-folio-viewer/edition-folio-viewer.component.html
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-convolute/edition-folio-viewer/edition-folio-viewer.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-convolute/edition-folio-viewer/edition-folio-viewer.component.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-convolute/edition-folio-viewer/folio.service.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-convolute/edition-folio-viewer/folio.service.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-sheets.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-sheets.component.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-tka/edition-tka-description/edition-tka-description.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-tka/edition-tka-description/edition-tka-description.component.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-tka/edition-tka-table/edition-tka-table.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-tka/edition-tka-table/edition-tka-table.component.ts
src/testing/mock-data/mockEditionData.ts

This PR unifies the signature of the selectSvgSheet method. It now uses the object `{ complexId: string; sheetId: string }` throughout the app. Before there was an alternative approach in some places.

refactor(edition): unify signature of selectSvgSheet method

---

.github/workflows/ci_workflow.yml

This PR introduces a step in the dev build process to remove existing files prior to updating the folder. Previously, new files were merely added, resulting in an accumulation of outdated files.

ci(gh-actions): remove existing files when updating dev

---

.github/workflows/ci_workflow.yml

This PR introduces a step in the dev build process to remove existing files prior to updating the folder. Previously, new files were merely added, resulting in an accumulation of outdated files.
Second try since #1604 went wrong and deleted the complete gh-pages folder.

ci(gh-actions): remove existing files when updating dev (II)

---

.github/workflows/ci_workflow.yml

This PR brings back the test build on any branch. Recently, the test build was only executed on dev and main.

ci(gh-actions): bring back test build on any branch

---

src/app/core/navbar/navbar.component.spec.ts
src/app/shared/scroll-to-top/scroll-to-top.component.html
src/app/shared/scroll-to-top/scroll-to-top.component.scss
src/app/shared/scroll-to-top/scroll-to-top.component.spec.ts
src/app/shared/scroll-to-top/scroll-to-top.component.ts
src/app/shared/shared.module.ts
src/app/shared/table/table.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-convolute/edition-convolute.component.spec.ts
src/app/views/edition-view/edition-view.component.html
src/app/views/edition-view/edition-view.component.spec.ts

This PR introduces a button that scrolls to the top of the page. Will be automatically displayed on all edition pages since these are expected to have the most extended content.

feat(edition): add ScrollToTop button to edition view

---

.github/workflows/ci_workflow.yml

A regression in Node 22.5.0 prevents `yarn install` from running and in turns prevents CI from completing successfully. This regression was fixed in 22.5.1. So this commit ensures that CI is using the correct version by naming it explicitly.

ci(gh-actions): pin fixed node version temporarily

---

src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-convolute/edition-folio-viewer/folio.service.spec.ts
src/app/views/edition-view/models/folio-calculation.model.ts
src/app/views/edition-view/models/folio.model.ts
src/testing/mock-data/mockEditionData.ts

This PR adds an option to place folio items next to a system (above or below), to indicate non-system items.

feat(edition): add option to place folio items next to systems

---

src/app/views/edition-view/edition-jumbotron/edition-jumbotron.component.html
src/app/views/edition-view/edition-jumbotron/edition-jumbotron.component.spec.ts

This PR removes the off-topic landscape image from the awg jumbotron.

fix(edition): remove landscape image from jumbotron

---

.github/workflows/ci_workflow.yml

This PR switches the node version used in the gh actions back to latest v22. Thus reverts the temporary fix in #1660.

ci(gh-actions): switch back to latest node v22

---

src/app/shared/error-alert/error-alert.component.html
src/app/shared/error-alert/error-alert.component.spec.ts
src/app/shared/error-alert/error-alert.component.ts
src/app/shared/shared.module.ts
src/app/views/data-view/data-outlets/resource-detail/resource-detail.component.html
src/app/views/data-view/data-outlets/search-panel/search-panel.component.html
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-graph/edition-graph.component.html
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-graph/edition-graph.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-intro/edition-intro.component.html
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-intro/edition-intro.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/edition-report.component.html
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/edition-report.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-sheets.component.html
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-sheets.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-sheets.component.ts

This PR adds a loading spinner to all parts of the edition views and introduces a shared ErrorAlertComponent to handle errors.

fix(edition): improve handling of errors and loading state

---

src/assets/data/edition/series/2/section/2a/m38/textcritics.json
src/assets/img/edition/series/2/section/2a/m38/M38_Sk2-1von1-final.svg
src/assets/img/edition/series/2/section/2a/m38/M38_Sk3-2von5-final.svg

This PR optimizes the formatting (no content changed) of the updated svg files in #1748 and fixes a typo in the textcritics for m38.

fix(assets): fix files for m38

---

src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description-corrections/source-description-corrections.component.html
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description-corrections/source-description-corrections.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-tka/edition-tka-table/edition-tka-table.component.html
src/assets/data/edition/series/1/section/5/op12/source-description.json
src/assets/data/edition/series/1/section/5/op25/source-description.json

This PR adjusts the formatting of the recently added corrections.
It also hides the tka table if there are no corrections provided.
In addition, it slightly highlights the blockHeaders in the tka tables to give them some more visual separation functionality.

fix(edition): improve formatting and display of sourceDesc corrections

---

src/app/views/edition-view/data/edition-glyphs.data.ts
src/assets/data/edition/series/1/section/5/op3/source-description.json

Just a small fix of formatting for op3 corrections.
Also adds missing glyphs for sf and sp and fixes typos.

fix(assets): fix corrections op3: E

---

src/app/views/edition-view/data/edition-glyphs.data.ts
src/assets/data/edition/series/1/section/5/op3/source-description.json

This PR adds missing glyphs for note values and applies them in the assets where needed.

fix(edition): add missing glyphs for note values

---

src/app/app.component.spec.ts
src/app/app.component.ts
src/app/core/footer/footer.component.ts
src/app/core/interceptors/caching/caching.interceptor.ts
src/app/core/interceptors/loading/loading.interceptor.ts
src/app/core/navbar/navbar.component.html
src/app/core/navbar/navbar.component.ts

This PR is a test to fix a SonarCloud analysis issue stating fields that are only assigned in the constructor should be made read-only.

fix(app): make fields only assigned in the constructor readonly

---

src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-sheets.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-sheets.component.ts

This PR updates the sheet view to display text editions first if they are available (instead of sketch editions). If no text editions are available it falls back to sketch editions.

fix(edition): display text editions by default if available

---

angular.json

This PR migrates the schematicCollections to angular-eslint which was forgotten in #2025

build(app): migrate schematicCollections to angular-eslint

---

.github/workflows/ci_workflow.yml
angular.json
src/polyfills.ts

This PR replaces the deprecated sonarcloud-github-action with the sonarqube-scan-action and moves the polyfills for localize to the angular.json as recommended.

build(app): clean up

---

src/app/shared/disclaimer-workeditions/disclaimer-workeditions.component.html
src/app/shared/disclaimer-workeditions/disclaimer-workeditions.component.spec.ts
src/app/shared/disclaimer-workeditions/disclaimer-workeditions.component.ts
src/app/shared/shared.module.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/textcritics-list/textcritics-list.component.html
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/textcritics-list/textcritics-list.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/textcritics-list/textcritics-list.component.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-nav/edition-svg-sheet-nav-item/edition-svg-sheet-nav-item.component.html
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-nav/edition-svg-sheet-nav-item/edition-svg-sheet-nav-item.component.spec.ts
src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-nav/edition-svg-sheet-nav-item/edition-svg-sheet-nav-item.component.ts

This PR moves the workedition disclaimer into a separate component to reuse it where needed. It also adds the disclaimer to the tka for work editions.

feat(edition): add disclaimer button to WE textcritics

---

src/assets/data/edition/series/2/section/2a/m40/textcritics.json
src/assets/data/edition/series/2/section/2a/m41/textcritics.json

This PR adds spans to the glyphs in m40 and 41, which was forgotten in #1504 and #1505

fix(assets): add spans to glyphs in m40–41

---

src/assets/data/edition/series/1/section/5/op23/source-description.json
src/assets/data/edition/series/1/section/5/op3/source-description.json
src/assets/data/edition/series/1/section/5/op4/source-description.json

This PR fixes some wrong syntax for empty item links that was overlooked in AWG I/5.

fix(assets): fix empty item links in AWG I/5

---

src/assets/data/edition/series/2/section/2a/m32/textcritics.json

This PR fixes the syntax for the glyphs in m32 that have an editorial bracket.

fix(assets): fix glyphs with brackets in m32
