src/app/shared/modal/modal.component.ts
=> fix(edition): adjust modal.components.ts

src/assets/img/edition/series/1/section/5/op25/M317_Sk2_1_2_1von1_220715_path.svg
=> fix(assets): adjust eighth flag in svg of M 317 Sk2.1.2

src/assets/data/edition/series/1/section/5/op25/source-description.json
adjust 'content' of fol. 1r & 1v, add 'annotations' in source B of op. 25
=> fix(assets): adjust source description (B) for op. 25

src/assets/data/edition/series/1/section/5/op12/textcritics.json
=> fix(assets): minor fixes in textcritics of M212_Sk2

src/assets/data/edition/series/1/section/5/op25/textcritics.json
- add svgGroupId (NB: class="tka")
- change html encoding of forte symbol (&#119185;) to "&#x1D191;"
=> feat(assets): M317 TF1 add svgGroupId

src/assets/data/edition/series/1/section/5/op25/source-description.json
minor correction in source description for M 317 Sk4
=> fix(assets): fix typo in source description for M 317 Sk4

src/assets/data/edition/series/1/section/5/op12/source-list.json
corrections of source list of op. 12 (source C) in comparison to print version of KB
=> fix(assets): corrections of source list in comparison to print version

SECURITY.md
This PR adds a security policy file.
=> docs(app): create SECURITY.md

src/assets/data/edition/series/1/section/5/op12/source-description.json, src/assets/data/edition/series/1/section/5/op23/source-description.json
This PR fixes some minimal issues identified during today's jour fixe.
=> fix(assets): fix source descriptions op12 & 23

src/assets/data/edition/series/1/section/5/op12/source-description.json, src/assets/data/edition/series/1/section/5/op23/source-description.json
minor fixes in source description G + GH of op. 12
=> fix(assets): update source description op12

README.md
This PR adds another badge to the README
=> docs(README): add OSSF best pratices badge

CONTRIBUTING.md, README.md
This PR includes some additional documentation on how to use, start, build and test the app, as well as how to raise issues and conctact the mainteiners. Contribution guidelines are updated with some more details as well.
=> docs(app): update README and CONTRIBUTING files

src/assets/data/edition/series/1/section/5/op23/source-list.json
Fix tabs + " in source-list of op. 23
=> fix(assets): fix tabs and quotes in source-list op. 23

src/app/shared/twelve-tone-spinner/twelve-tone-spinner.component.html, src/app/shared/twelve-tone-spinner/twelve-tone-spinner.component.scss, src/app/shared/twelve-tone-spinner/twelve-tone-spinner.component.spec.ts, src/app/shared/twelve-tone-spinner/twelve-tone-spinner.component.ts, src/index.html, src/index.style.scss
This PR refactors the twelve-tone-spinner to simplify and the reduce the size of the component.
=> refactor(shared): simplify and reduce size of spinner

src/app/side-info/edition-info/edition-info.component.html, src/app/side-info/resource-info/resource-info.component.html, src/app/views/data-view/data-outlets/search-panel/fulltext-search-form/fulltext-search-form.component.html, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/edition-report.module.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description-corrections/index.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description-corrections/source-description-corrections.component.html, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description-corrections/source-description-corrections.component.spec.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description-corrections/source-description-corrections.component.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description.component.html, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description.component.spec.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description.component.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description.module.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-nav/edition-svg-sheet-nav-item/edition-svg-sheet-nav-item.component.html, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-tka/edition-tka.module.ts, src/app/views/edition-view/edition-view.component.html, src/app/views/edition-view/models/source-description.model.ts, src/assets/data/edition/series/1/section/5/op12/source-description.json, src/testing/mock-data/mockEditionData.ts
This PR adds the possibility to include correction lists in the source description of a source.
=> feat(edition): add corrections to source descriptions

src/app/shared/toast/toast.component.html, src/app/views/data-view/data-outlets/search-panel/extended-search-form/extended-search-form.component.html, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-list/source-list.component.html, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-viewer/edition-svg-sheet-viewer-switch/edition-svg-sheet-viewer-switch.component.html, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-tka/edition-tka-table/edition-tka-table.component.html
This PR fixes track-by indices for Angular's for-loops in templates that had been marked as expensive due to full object comparison.
=> fix(app): fix expensive track-by indices

src/app/core/core-models/index.ts, src/app/core/core-models/jdn-date.model.ts, src/app/core/services/conversion-service/conversion.service.spec.ts, src/app/core/services/conversion-service/conversion.service.ts, src/app/views/data-view/data-outlets/search-panel/search-panel.component.ts, src/app/views/data-view/data-outlets/search-panel/search-result-list/search-result-list.component.html
This PR simplifies link and date value converion.
=> fix(core): simplify conversion

src/app/core/services/conversion-service/conversion.service.ts, src/app/shared/router-link-button-group/router-link-button-group.component.html, src/app/shared/table/table.component.html, src/app/views/data-view/data-outlets/bibliography/bibliography-list/bibliography-list.component.html, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-footer/edition-svg-sheet-footer.component.html, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-viewer/edition-svg-sheet-viewer-nav/edition-svg-sheet-viewer-nav.component.html, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-viewer/edition-svg-sheet-viewer-switch/edition-svg-sheet-viewer-switch.component.html
This PR adds corresponding keyboard events to mouse events and improves typings for distinctSubject conversion. Those issues had been detected by Sonar Cloud analysis.
=> Fix some issues from Sonar Cloud analysis

README.md
This PR updates the installation/prerequisites section of the README, after upgrading to Yarn Modern.
=> docs(README): update install instructions

src/assets/data/edition/series/1/section/5/op3/source-description.json, src/assets/data/edition/series/1/section/5/op4/source-description.json
This PR adds cross-complex report links between op3 and op4.
=> fix(assets): activate cross-complex report links in op3 and op4

src/app/shared/address/address.component.spec.ts, src/app/shared/codemirror/codemirror.component.spec.ts, src/app/shared/external-link/external-link.directive.spec.ts, src/app/shared/heading/heading.component.spec.ts, src/app/shared/json-viewer/json-viewer.component.spec.ts, src/app/shared/modal/modal.component.spec.ts, src/app/shared/table/table-pagination/table-pagination.component.spec.ts, src/app/shared/table/table.component.spec.ts, src/app/shared/toast/toast.component.spec.ts, src/app/shared/toast/toast.service.spec.ts, src/app/side-info/resource-info/resource-info.component.spec.ts, src/app/views/contact-view/contact-view.component.spec.ts, src/app/views/data-view/data-outlets/bibliography/bibliography-detail/bibliography-detail.component.spec.ts, src/app/views/data-view/data-outlets/resource-detail/resource-detail-html/resource-detail-html-content/props/props.component.spec.ts, src/app/views/data-view/data-outlets/resource-detail/resource-detail-html/resource-detail-html-content/resource-detail-html-content.component.spec.ts, src/app/views/data-view/data-outlets/resource-detail/resource-detail-html/resource-detail-html.component.spec.ts, src/app/views/data-view/data-outlets/resource-detail/resource-detail-json-raw/resource-detail-json-raw.component.spec.ts, src/app/views/data-view/data-outlets/search-overview.component.spec.ts, src/app/views/data-view/data-view.component.spec.ts, src/app/views/edition-view/edition-outlets/edition-row-tables/edition-row-tables.component.spec.ts, src/app/views/edition-view/services/edition.service.spec.ts, src/app/views/page-not-found-view/page-not-found-view.component.spec.ts, src/app/views/structure-view/structure-view.component.spec.ts
=> test(app): fix syntax of some more tests

.github/workflows/ci_workflow.yml
This PR includes latest node version for workflow tests.
=> ci(gh-actions): include node 22 in workflow

src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description-corrections/source-description-corrections.component.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description-details/source-description-details.component.ts
=> docs(edition): add JSDocs to new SourceDescription sub-classes

src/assets/data/edition/series/1/section/5/op25/source-list.json
This PR fixes the source siglum for op25 E.
=> fix(assets): fix addendum for source E in op25

src/app/views/edition-view/data/edition-glyphs.data.ts, src/assets/data/edition/series/1/section/5/op12/source-description.json
This PR adjust the newly added corrections for op12 to the newly updated corrections model.
It also adds some missing glyphs.
=> fix(edition): fix corrections

src/assets/data/edition/series/1/section/5/op25/source-description.json
add list of corrections in source description of op. 25: source_E_corr1 + source_E_corr2
=> feat(assets): add corrections in op25: E

src/assets/data/edition/series/1/section/5/op25/source-description.json
remove disclaimer for corrections
=> fix(assets):  remove disclaimer for corrections of op25

src/assets/data/edition/series/1/section/5/op3/source-description.json
add corrections for op. 3: source_B_corr
=> feat(assets): add corrections in op3: B

src/assets/data/edition/series/1/section/5/op3/source-description.json
Just a small fix of indentations.
=> fix(assets): fix formatting of corrections op3: B

src/assets/data/edition/series/1/section/5/op3/source-description.json
add corrections for Op. 3: source_Aa_corr1+2 + source_Ab_corr1+2
=> feat(assets): add corrections in Op. 3: Aa+Ab

src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description-corrections/source-description-corrections.component.html, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description-corrections/source-description-corrections.component.spec.ts
This PR adds a border to the corrections to improve styling.
=> style(edition): improve display of corrections

src/styles.scss
This PR adds display=swap to web font loading to decrease display time of text.
=> style(app): swap display of web font

src/assets/data/edition/series/1/section/5/op3/source-description.json
add corrections for Op. 3: source_C_corr
=> feat(assets): add corrections in op3: C

src/assets/data/edition/series/1/section/5/op3/source-description.json
Just a small fix for formattings.
=> fix(assets): fix formatting of corrections op3: C

src/assets/data/edition/series/1/section/5/op3/source-description.json
add corrections for Op. 3: source_Eabcde_corr
+ minor fix in source_Ab_corr2
=> feat(assets): add corrections in op3: E

src/assets/data/edition/series/1/section/5/op3/source-description.json
This PR fixes some typos and corrects the formatting for those corrections of op3 added recently.
=> fix(assets): fix formatting of corrections op3: F–H

.vscode/settings.json, src/assets/data/edition/series/1/section/5/op3/source-description.json
add corrections for Op3: source_I_corr_1_2 + source_J_corr
=> feat(assets): add corrections for Op3: I + J

src/assets/data/edition/series/1/section/5/op4/source-description.json
add corrections for Op4: source_A_corr
=> feat(assets): add corrections for Op4: A

src/assets/data/edition/series/1/section/5/op4/source-description.json
add corrections in Op4: source_Dab_corr
=> feat(assets): add corrections in Op4: D

src/app/shared/abbr/abbr.directive.spec.ts, src/app/shared/abbr/abbr.directive.ts, src/app/shared/external-link/external-link.directive.spec.ts, src/app/shared/shared.module.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description.component.html, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description.component.spec.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-list/source-list.component.html, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-list/source-list.component.spec.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-tka/edition-tka-table/edition-tka-table.component.html, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-tka/edition-tka-table/edition-tka-table.component.spec.ts
This PR adds an abbreviation directive to resolve most abbreviations used in the critical report.
=> feat(shared): add abbreviation directive

.github/workflows/ci_workflow.yml, README.md, package.json, src/app/core/footer/footer-declaration/footer-declaration.component.html, src/app/core/footer/footer-declaration/footer-declaration.component.spec.ts, src/app/core/navbar/navbar.component.html, src/app/core/navbar/navbar.component.spec.ts, src/app/views/contact-view/contact-view.component.html, src/app/views/home-view/home-view.component.html, src/app/views/home-view/home-view.component.ts, src/index.html
BREAKING CHANGE: This ends the status of the app as a prototype.
This PR removes references to prototype.
=> feat(app): move away from prototype

src/app/side-info/edition-info/edition-info.component.html, src/app/side-info/edition-info/edition-info.component.ts, src/app/views/edition-view/models/edition-outline.model.ts
This PR open the side menu section dynamically.
=> fix(side-info): open sections dynamically

src/app/core/navbar/navbar.component.html, src/app/core/navbar/navbar.component.spec.ts, src/app/core/navbar/navbar.component.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-graph/edition-graph.component.html, src/app/views/edition-view/edition-outlets/edition-series-detail/edition-section-detail/edition-section-detail-disclaimer/edition-section-detail-disclaimer.component.html, src/app/views/edition-view/edition-outlets/edition-series-detail/edition-section-detail/edition-section-detail-disclaimer/edition-section-detail-disclaimer.component.spec.ts
This PR improves the wording of dicslaimers and the handling of icons in the navbar.
=> refactor(app): improve wordings and icons

src/app/views/edition-view/models/edition-outline.model.ts, src/app/views/edition-view/services/edition-outline.service.spec.ts
This PR fixes a wrong check for AWG III/5 in the outline model.
=> fix(edition): fix check for section III/5 in outline model

src/app/app.component.html, src/app/core/view-container/view-container.component.html, src/app/core/view-container/view-container.component.spec.ts, src/app/views/contact-view/contact-view.component.spec.ts, src/app/views/contact-view/contact-view.component.ts, src/app/views/data-view/data-outlets/resource-detail/resource-detail.component.ts, src/app/views/data-view/data-view.component.spec.ts, src/app/views/data-view/data-view.component.ts, src/app/views/edition-view/edition-view.component.spec.ts, src/app/views/edition-view/edition-view.component.ts, src/app/views/home-view/home-view.component.spec.ts, src/app/views/home-view/home-view.component.ts, src/app/views/structure-view/structure-view.component.spec.ts, src/app/views/structure-view/structure-view.component.ts, src/assets/themes/css/main.css, src/assets/themes/scss/main.scss
This PR renames the routeToSidenav method to navigateToSideOutlet
=> refactor(app): rename routeToSidenav method

package.json, src/app/shared/alert-info/alert-info.component.ts, yarn.lock
This PR dies some final clean up before v1.
=> fix(app): cleanup

README.md
This PR updates the project image of the README.
=> docs(README): update project image

src/assets/data/edition/series/1/section/5/op25/source-description.json
Update source-description.json Op25
=> fix(assets): Update source-description.json Op25

src/app/shared/fullscreen-toggle/fullscreen-toggle.component.html, src/app/shared/fullscreen-toggle/fullscreen-toggle.component.spec.ts, src/app/shared/fullscreen-toggle/fullscreen-toggle.component.ts, src/app/shared/shared.module.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-graph/edition-graph.component.html, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-graph/edition-graph.component.spec.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-graph/edition-graph.component.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/edition-report.component.spec.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-accolade.component.html, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-accolade.component.scss, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-accolade.component.spec.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-accolade.component.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-footer/edition-svg-sheet-footer.component.html, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-footer/edition-svg-sheet-footer.component.spec.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-footer/edition-svg-sheet-footer.component.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-viewer/edition-svg-sheet-viewer-nav/edition-svg-sheet-viewer-nav.component.scss, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-accolade/edition-svg-sheet-viewer/edition-svg-sheet-viewer.component.scss, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-sheets.component.html, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-sheets.component.spec.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-sheets.component.ts, src/app/views/edition-view/models/textcritics.model.ts, src/app/views/edition-view/models/view-box.model.ts
This PR improves styling for sheet view nav buttons and sheet footer and adds a fullscreen option for the sheet viewer.
=> feat(edition): improve sheet view

src/assets/data/edition/edition-complexes.json
This PR fixes the incomplete homepage links in the edition-complexes.json file.
Fixes #1974
=> fix(assets): fix incomplete homepage links

src/assets/data/edition/series/1/section/5/op25/source-description.json, src/assets/data/edition/series/1/section/5/op25/svg-sheets.json
=> fix(assets): small fixes for op25

src/app/views/edition-view/services/edition-svg-drawing.service.spec.ts, src/app/views/edition-view/services/edition-svg-drawing.service.ts
This PR fixes the broken toggling of single supplied classes.
=> fix(edition): fix toggling of supplied classes

src/assets/data/edition/series/1/section/2/op22/textcritics.json, src/assets/data/edition/series/1/section/3/op19/textcritics.json
fixes in row tables of op19 & op22
=> fix(assets): row tables revisited

src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description-contents/source-description-contents.component.html
This PR includes a small fix for the sourceDesc tables.
=> fix(edition): fix role of sourceDesc table

src/assets/data/edition/series/2/section/2a/m29/folio-convolute.json, src/assets/data/edition/series/2/section/2a/m29/source-description.json, src/assets/data/edition/series/2/section/2a/m29/svg-sheets.json, src/assets/data/edition/series/2/section/2a/m30/folio-convolute.json, src/assets/data/edition/series/2/section/2a/m31/folio-convolute.json, src/assets/data/edition/series/2/section/2a/m38/source-description.json, src/assets/data/edition/series/2/section/2a/m43/folio-convolute.json, src/assets/data/edition/series/2/section/2a/m43/svg-sheets.json
This PR syncs the folio overviews for some of the complexes in AWG II/2b.
=> fix(assets): sync folio overview

src/assets/data/edition/series/2/section/2a/m43/source-description.json
This PR adjusts the physical description in source A if m43.
Supersedes #2182
Co-authored by: @chael-mi
=> fix(assets): adjust physDesc in m43 A

src/assets/data/edition/series/1/section/5/m144/textcritics.json
fix missing italics in title of _Kunfttag I_
=> fix(assets): fix missing italics in title of Kunfttag I

.github/workflows/ci_workflow.yml, .github/workflows/codeql.yml, .github/workflows/dependency-review.yml, .github/workflows/scorecards.yml, .github/workflows/visualize-repo.yml
This PR restricts the repo actions to be run only on the main repo.
=> ci(gh-actions): run actions only on main repo

.github/workflows/ci_workflow.yml, README.md, src/app/app.config.ts, src/app/core/core-data/logos.data.ts, src/app/core/core-data/meta.data.ts, src/app/views/home-view/home-view-card/home-view-card.component.spec.ts, src/app/views/page-not-found-view/page-not-found-view.component.spec.ts, src/app/views/page-not-found-view/page-not-found-view.component.ts, src/assets/data/edition/edition-complexes.json, src/index.html, src/testing/mock-data/mockEditionData.ts
This PR fixes the links in the awg-app to the project website since it was under reconstruction.
=> fix(app): fix links to project page

src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/textcritics-list/textcritics-list.component.html, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/textcritics-list/textcritics-list.component.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-tka/edition-tka-evaluations/edition-tka-evaluations.component.spec.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-tka/edition-tka-evaluations/edition-tka-evaluations.component.ts, src/testing/mock-data/mockEditionData.ts
This PR adds logic to render glyphs in tka evaluations.
=> fix(edition): render glyphs in tka evaluations

src/app/shared/fullscreen-toggle/fullscreen-toggle.component.spec.ts, src/app/shared/fullscreen-toggle/fullscreen-toggle.component.ts, src/app/views/data-view/data-outlets/search-panel/search-panel.component.spec.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-graph/edition-graph.component.spec.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-intro/edition-intro-content/edition-intro-content.component.spec.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-intro/edition-intro-content/edition-intro-content.component.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description-contents/source-description-contents.component.spec.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description-contents/source-description-contents.component.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description-corrections/source-description-corrections.component.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description-details/source-description-details.component.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description-writing-materials/source-description-writing-materials.component.spec.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description-writing-materials/source-description-writing-materials.component.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-description/source-description.component.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-report/source-evaluation/source-evaluation.component.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-sheets/edition-sheets.component.spec.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-tka/edition-tka-table/edition-tka-table.component.spec.ts, src/app/views/edition-view/edition-outlets/edition-complex/edition-detail/edition-tka/edition-tka-table/edition-tka-table.component.ts, src/app/views/edition-view/edition-outlets/edition-series-detail/edition-section-detail/edition-section-detail-intro-card/edition-section-detail-intro-card.component.ts, src/app/views/edition-view/edition-outlets/edition-series-detail/edition-section-detail/edition-section-detail-placeholder/edition-section-detail-placeholder.component.ts
This PR shortcuts some imports and adds missing documentation.
=> refactor(app): fix imports and docs
